import { Building2, GraduationCap, Mail, UsersRound } from 'lucide-react'

const members = [
  { name: 'Thiều Thị Thu Huyền', role: 'Trưởng nhóm / Project Lead & UI Architecture', initials: 'TH' },
  { name: 'Huỳnh Ngọc Minh Thảo', role: 'Frontend Developer', initials: 'MT' },
  { name: 'Nguyễn Thu Thảo', role: 'Blockchain Logic Developer', initials: 'TT' },
  { name: 'Lê Thị Kim Oanh', role: 'PoS & Smart Contract Specialist', initials: 'KO' },
  { name: 'Trần Thị Thanh Hoàng', role: 'Research & Documentation', initials: 'TH' },
  { name: 'Nguyễn Thị Mỹ Chi', role: 'Data Analyst & QA Tester', initials: 'MC', description: 'Phân tích dữ liệu mô phỏng, kiểm thử chất lượng hệ thống và tài liệu báo cáo.' },
]

export default function TabTeam() {
  return (
    <div className="mx-auto max-w-5xl space-y-5">
      <section className="rounded-2xl border border-slate-800 bg-slate-900/80 p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-4"><span className="grid size-14 place-items-center rounded-2xl border border-emerald-300/20 bg-emerald-300/[0.07] text-emerald-200"><Building2 size={23} /></span><div><p className="font-mono text-[9px] uppercase tracking-[0.14em] text-emerald-300">Academic project</p><h3 className="mt-1 text-lg font-semibold text-slate-100">Đại Học Ngân Hàng TP.HCM</h3><p className="mt-1 text-[10px] text-slate-400">Khoa Khoa học dữ liệu · HUB</p></div></div><span className="rounded-full border border-slate-700 bg-[#0b0f19]/60 px-3 py-1.5 font-mono text-[8px] uppercase tracking-[0.08em] text-slate-400">HUB Blockchain Lab</span></div></section>
      <section className="grid gap-3 sm:grid-cols-2" aria-label="Project advisors and team"><article className="flex items-center gap-4 rounded-2xl border border-slate-800 bg-slate-900/75 p-5"><span className="grid size-11 place-items-center rounded-xl border border-sky-300/20 bg-sky-300/[0.07] text-sky-200"><GraduationCap size={20} /></span><div><span className="font-mono text-[8px] uppercase tracking-[0.12em] text-slate-500">Faculty Supervisor / Advisor</span><h4 className="mt-1 text-xs font-semibold text-slate-100">TS. Nguyễn Hoài Đức</h4></div></article><article className="flex items-center gap-4 rounded-2xl border border-slate-800 bg-slate-900/75 p-5"><span className="grid size-11 place-items-center rounded-xl border border-amber-300/20 bg-amber-300/[0.07] text-amber-100"><UsersRound size={19} /></span><div><span className="font-mono text-[8px] uppercase tracking-[0.12em] text-slate-500">Nhóm thực hiện</span><h4 className="mt-1 text-xs font-semibold text-slate-100">6 sinh viên · Khoa Khoa học dữ liệu</h4></div></article></section>
      <section className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/80"><header className="flex items-center justify-between border-b border-slate-800 px-5 py-4 sm:px-6"><div><h3 className="text-sm font-semibold text-slate-100">Project team</h3><p className="mt-1 font-mono text-[8px] uppercase tracking-[0.1em] text-slate-500">HUB · Blockchain learning simulator · 6 students + 1 faculty advisor</p></div><UsersRound size={16} className="text-emerald-300" /></header><div className="divide-y divide-slate-800/80 px-5 sm:px-6">{members.map((member, index) => <article key={member.name} className="flex items-start gap-3 py-4"><span className={`mt-0.5 grid size-10 shrink-0 place-items-center rounded-full border font-mono text-[9px] font-semibold ${index === 0 ? 'border-amber-300/25 bg-amber-300/[0.08] text-amber-100' : 'border-slate-700 bg-slate-800 text-slate-300'}`}>{member.initials}</span><div className="min-w-0 flex-1"><h4 className="text-xs font-semibold text-slate-100">{member.name}</h4><p className="mt-1 text-[10px] leading-5 text-slate-400">{member.role}</p>{member.description && <p className="mt-1 text-[10px] leading-5 text-slate-500">{member.description}</p>}</div>{index === 0 && <span className="rounded-full border border-amber-300/20 px-2.5 py-1 font-mono text-[8px] text-amber-100">LEAD</span>}</article>)}</div></section>
      <p className="flex items-center gap-2 px-1 text-[9px] text-slate-600"><Mail size={12} />Thông tin nhóm phục vụ nhận diện dự án học tập.</p>
    </div>
  )
}